#! /usr/bin/env bash

source ./pipeline-monitor.env

gitlabApiUrl="https://gitlab.com/api/v4"

function curlGitlab {
    path="${1}"
    curl "${gitlabApiUrl}${path}" \
      -H "Private-Token: ${gitlabApiToken}" \
      -s
}

function getPipelines {
    projectId="${1}"
    curlGitlab "/projects/${projectId}/pipelines?ref=master&per_page=10"
}

function getProject {
    projectId="${1}"
    curlGitlab "/projects/${projectId}"
}

function getLastPipelineStatus {
    projectId="${1}"
    getPipelines "${projectId}" | jq -r '.[0].status'
}

function getProjectName {
    projectId="${1}"
    getProject "${projectId}" | jq -r '.name'
}

function notify {
    summary="${1}"
    body="${2}"
    notify-send \
        "${summary}" \
        "$(echo -e "${body}")" \
        -u critical
}

function main {
    failedPipelines=()

    for project in "${projects[@]}"; do
        if [ $(getLastPipelineStatus "${project}") == "failed" ]; then
            failedPipelines+=("${project}")
        fi
    done

    if [ ${#failedPipelines[@]} -ne 0 ]; then
        for project in "${failedPipelines[@]}"; do
            projectName="$(getProjectName "${project}")"
            body="${body}• ${projectName}\n"
        done

        notify "The following pipelines are failing:" "${body}"
    fi
}

main
